# Generated by Django 3.1 on 2020-08-15 02:05

from django.db import migrations, models
import scriptTools.timeTools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsBand',
            fields=[
                ('brandid', models.AutoField(primary_key=True, serialize=False, verbose_name='brandid')),
                ('createtime', models.CharField(blank=True, default=scriptTools.timeTools.dateStdTime, max_length=50, verbose_name='createtime')),
                ('state', models.CharField(blank=True, default='可用', max_length=50, verbose_name='state')),
                ('brandaddress', models.CharField(blank=True, default='未填写', max_length=50, verbose_name='brandaddress')),
                ('brandtelephone', models.CharField(blank=True, default='未填写', max_length=50, verbose_name='brandtelephone')),
                ('brandname', models.CharField(max_length=50, unique=True, verbose_name='brandname')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('goodid', models.AutoField(primary_key=True, serialize=False, verbose_name='goodid')),
                ('createtime', models.CharField(blank=True, default=scriptTools.timeTools.dateStdTime, max_length=50, verbose_name='createtime')),
                ('state', models.CharField(blank=True, default='在售', max_length=50, verbose_name='state')),
                ('brandname', models.CharField(blank=True, default='未填写', max_length=50, verbose_name='brandname')),
                ('goodintroduce', models.CharField(blank=True, default='', max_length=50, verbose_name='goodintroduce')),
                ('goodname', models.CharField(max_length=50, unique=True, verbose_name='goodname')),
                ('goodprice', models.CharField(max_length=50, verbose_name='goodprice')),
            ],
        ),
    ]
