# Generated by Django 3.1 on 2020-08-15 01:34

from django.db import migrations, models
import scriptTools.timeTools
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VipsGood',
            fields=[
                ('vipgoodid', models.AutoField(primary_key=True, serialize=False, verbose_name='vipgoodid')),
                ('vipgooduuid', models.CharField(blank=True, default=uuid.uuid1, max_length=50, verbose_name='vipgooduuid')),
                ('createtime', models.CharField(blank=True, default=scriptTools.timeTools.dateStdTime, max_length=50, verbose_name='createtime')),
                ('state', models.CharField(blank=True, default='未发货', max_length=50, verbose_name='state')),
                ('sendtime', models.CharField(blank=True, default='-1', max_length=50, verbose_name='sendtime')),
                ('vipname', models.CharField(max_length=50, verbose_name='vipname')),
                ('viptelephone', models.CharField(max_length=50, verbose_name='viptelephone')),
                ('goodid', models.CharField(max_length=50, verbose_name='goodid')),
                ('goodname', models.CharField(max_length=50, verbose_name='goodname')),
                ('goodprice', models.CharField(max_length=50, verbose_name='goodprice')),
                ('staffid', models.CharField(max_length=50, verbose_name='staffid')),
                ('staff', models.CharField(max_length=50, verbose_name='staff')),
            ],
        ),
        migrations.CreateModel(
            name='VipsInfo',
            fields=[
                ('vipid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='vipid')),
                ('vipuuid', models.CharField(blank=True, default=uuid.uuid1, max_length=50, verbose_name='vipuuid')),
                ('createtime', models.CharField(blank=True, default=scriptTools.timeTools.dateStdTime, max_length=50, verbose_name='createtime')),
                ('summoney', models.CharField(default='0', max_length=50, verbose_name='summoney')),
                ('remainmoney', models.CharField(default='0', max_length=50, verbose_name='remainmoney')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('telephone', models.CharField(max_length=50, unique=True, verbose_name='telephone')),
                ('birthday', models.CharField(max_length=50, verbose_name='birthday')),
                ('staffid', models.CharField(max_length=50, verbose_name='staffid')),
                ('staff', models.CharField(max_length=50, verbose_name='staff')),
            ],
        ),
        migrations.CreateModel(
            name='VipsProj',
            fields=[
                ('vipprojid', models.AutoField(primary_key=True, serialize=False, verbose_name='vipprojid')),
                ('vipprojuuid', models.CharField(blank=True, default=uuid.uuid1, max_length=50, verbose_name='vipprojuuid')),
                ('createtime', models.CharField(blank=True, default=scriptTools.timeTools.dateStdTime, max_length=50, verbose_name='createtime')),
                ('state', models.CharField(blank=True, default='未使用', max_length=50, verbose_name='state')),
                ('usetime', models.CharField(blank=True, default='-1', max_length=50, verbose_name='usetime')),
                ('vipname', models.CharField(max_length=50, verbose_name='vipname')),
                ('viptelephone', models.CharField(max_length=50, verbose_name='viptelephone')),
                ('projid', models.CharField(max_length=50, verbose_name='projid')),
                ('projname', models.CharField(max_length=50, verbose_name='projname')),
                ('projprice', models.CharField(max_length=50, verbose_name='projprice')),
                ('staffid', models.CharField(max_length=50, verbose_name='staffid')),
                ('staff', models.CharField(max_length=50, verbose_name='staff')),
            ],
        ),
        migrations.CreateModel(
            name='VipsRechange',
            fields=[
                ('viprechangeid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='viprechangeid')),
                ('viprechangeuuid', models.CharField(blank=True, default=uuid.uuid1, max_length=50, verbose_name='viprechangeuuid')),
                ('createtime', models.CharField(blank=True, default=scriptTools.timeTools.dateStdTime, max_length=50, verbose_name='createtime')),
                ('vipname', models.CharField(max_length=50, verbose_name='vipname')),
                ('viptelephone', models.CharField(max_length=50, verbose_name='viptelephone')),
                ('rechangemoney', models.CharField(max_length=50, verbose_name='rechangemoney')),
                ('staffid', models.CharField(max_length=50, verbose_name='staffid')),
                ('staff', models.CharField(max_length=50, verbose_name='staff')),
            ],
        ),
    ]
