# Generated by Django 3.1 on 2020-08-11 10:03

from django.db import migrations, models
import scriptTools.timeTools
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VipsConsume',
            fields=[
                ('vipconsumeid', models.AutoField(primary_key=True, serialize=False, verbose_name='vipconsumeid')),
                ('vipconsumeuuid', models.CharField(blank=True, default=uuid.uuid1, max_length=50, verbose_name='vipconsumeuuid')),
                ('createtime', models.CharField(blank=True, default=scriptTools.timeTools.dateStdTime, max_length=50, verbose_name='createtime')),
                ('gooduuid', models.CharField(max_length=50, verbose_name='gooduuid')),
                ('goodname', models.CharField(max_length=50, verbose_name='goodname')),
                ('goodmoney', models.CharField(max_length=50, verbose_name='goodmoney')),
                ('staffuuid', models.CharField(max_length=50, verbose_name='staffuuid')),
                ('staff', models.CharField(max_length=50, verbose_name='staff')),
            ],
        ),
        migrations.CreateModel(
            name='VipsInfo',
            fields=[
                ('vipid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='vipid')),
                ('vipuuid', models.CharField(blank=True, default=uuid.uuid1, max_length=50, verbose_name='vipuuid')),
                ('createtime', models.CharField(blank=True, default=scriptTools.timeTools.dateStdTime, max_length=50, verbose_name='createtime')),
                ('summoney', models.CharField(default='0', max_length=50, verbose_name='summoney')),
                ('remainmoney', models.CharField(default='0', max_length=50, verbose_name='remainmoney')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('telephone', models.CharField(max_length=50, unique=True, verbose_name='telephone')),
                ('birthday', models.CharField(max_length=50, verbose_name='birthday')),
                ('staffuuid', models.CharField(max_length=50, verbose_name='staffuuid')),
                ('staff', models.CharField(max_length=50, verbose_name='staff')),
            ],
        ),
        migrations.CreateModel(
            name='VipsProj',
            fields=[
                ('vipprojid', models.AutoField(primary_key=True, serialize=False, verbose_name='vipprojid')),
                ('createtime', models.CharField(blank=True, default=scriptTools.timeTools.dateStdTime, max_length=50, verbose_name='createtime')),
                ('vipprojuuid', models.CharField(max_length=50, verbose_name='vipprojuuid')),
                ('vipprojname', models.CharField(max_length=50, verbose_name='vipprojname')),
                ('vipprojprice', models.CharField(max_length=50, verbose_name='vipprojprice')),
                ('staffuuid', models.CharField(max_length=50, verbose_name='staffuuid')),
                ('staff', models.CharField(max_length=50, verbose_name='staff')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('useTime', models.CharField(max_length=50, verbose_name='useTime')),
            ],
        ),
        migrations.CreateModel(
            name='VipsRechange',
            fields=[
                ('viprechangeid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='viprechangeid')),
                ('viprechangeuuid', models.CharField(blank=True, default=uuid.uuid1, max_length=50, verbose_name='viprechangeuuid')),
                ('createtime', models.CharField(blank=True, default=scriptTools.timeTools.dateStdTime, max_length=50, verbose_name='createtime')),
                ('vipname', models.CharField(max_length=50, verbose_name='vipname')),
                ('viptelephone', models.CharField(max_length=50, verbose_name='viptelephone')),
                ('rechangemoney', models.CharField(max_length=50, verbose_name='rechangemoney')),
                ('staffuuid', models.CharField(max_length=50, verbose_name='staffuuid')),
                ('staff', models.CharField(max_length=50, verbose_name='staff')),
            ],
        ),
    ]
