# Generated by Django 3.1 on 2020-08-10 05:22

from django.db import migrations, models
import uuid
import vips.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VipsInfo',
            fields=[
                ('vipid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='vipid')),
                ('vipuuid', models.UUIDField(default=uuid.uuid1, verbose_name='vipuuid')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('telephone', models.CharField(max_length=50, verbose_name='telephone')),
                ('birthday', models.CharField(max_length=50, verbose_name='birthday')),
                ('rechangetype', models.CharField(max_length=50, verbose_name='rechangetype')),
                ('summoney', models.CharField(max_length=50, verbose_name='summoney')),
                ('staff', models.CharField(max_length=50, verbose_name='staff')),
                ('remainmoney', models.CharField(max_length=50, verbose_name='remainmoney')),
                ('createtime', models.CharField(default=vips.models.dateStdTime, max_length=50, verbose_name='createtime')),
            ],
        ),
        migrations.CreateModel(
            name='VipsProj',
            fields=[
                ('vipprojid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='vipprojid')),
                ('vipprojuuid', models.UUIDField(default=uuid.uuid1, verbose_name='vipprojuuid')),
            ],
        ),
    ]
