# Generated by Django 3.1 on 2020-08-10 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vips', '0003_auto_20200810_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipsinfo',
            name='vipuuid',
            field=models.CharField(blank=True, default=uuid.uuid1, max_length=50, null=True, verbose_name='vipuuid'),
        ),
    ]
