# Generated by Django 3.1 on 2020-08-10 05:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vips', '0005_auto_20200810_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipsinfo',
            name='vipuuid',
            field=models.CharField(blank=True, default=uuid.uuid1, max_length=50, verbose_name='vipuuid'),
        ),
        migrations.AlterField(
            model_name='vipsproj',
            name='vipprojid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='vipprojid'),
        ),
    ]
