# Generated by Django 3.1 on 2020-08-13 07:34

from django.db import migrations, models
import scriptTools.timeTools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjInfo',
            fields=[
                ('projid', models.AutoField(primary_key=True, serialize=False, verbose_name='proid')),
                ('createtime', models.CharField(blank=True, default=scriptTools.timeTools.dateStdTime, max_length=50, verbose_name='createtime')),
                ('projintroduce', models.CharField(blank=True, default='未填写', max_length=50, verbose_name='projintroduce')),
                ('projname', models.CharField(max_length=50, verbose_name='projname')),
                ('projprice', models.CharField(max_length=50, verbose_name='projprice')),
            ],
        ),
    ]
